server:
  port: 3000
spring:
  application:
    name: telegram-adapter
  config:
    import: optional:configserver:http://user:password@localhost:8888/
  cloud:
    config:
      label: master
  data:
    redis:
      host: localhost
      port: 6379
      password: redis
      timeout: 60000
      database: 0

telegram-adapter:
  settings:
    movie-sending-delay: 3600000

service:
  movie-match:
    api:
      url: http://localhost:8080
management:
  server:
    port: 3001
  endpoints:
    web:
      exposure:
#         refresh context: curl -H "Content-Type: application/json" -d {} http://localhost:8081/actuator/refresh
        include: "*"
